### ISSUE TITLE
A-TextUiTesting :  < input.txt only reads the first line

### ISSUE THREAD

**Issue by l-shihao** [nus-tic4001-AY2122S1/forum#12]
As per title, from the result of `ACTUAL.TXT`, only the first line of `input.txt` got processed, the `Scanner.nextLine` even threw `NoSuchElementException: No line found`. 

Q: Is it because my duke did not use `String[] args` for taking arguments? I thought the `<` redirection is considered as `stdin`?

Attached part of my `runtest.sh`: (maybe a seperate issue for shortening below)
```
# compile the code into the bin folder, terminates if error occurred
if ! javac -Xlint:none -d ../out/production/ip ../src/main/java/duke/*.java ../src/main/java/duke/ui/* ../src/main/java/duke/storage/* ../src/main/java/duke/exception/* ../src/main/java/duke/parse/* ../src/main/java/duke/task/* ../src/main/java/duke/command/*
then
    echo "********** BUILD FAILURE **********"
    exit 1
fi

# run the program, feed commands from input.txt file and redirect the output to the ACTUAL.TXT
java -classpath ../out/production/ip/ duke.Duke < input.txt > ACTUAL.TXT
```
Output in the terminal: (test failed is fine, as I didn't put correct content in EXPECTED.TXT)

```
li@intel text-ui-test % bash runtest.sh
Note: ../src/main/java/duke/ui/Message.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Exception in thread "main" java.util.NoSuchElementException: No line found
	at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
	at duke.Duke.start(Duke.java:39)
	at duke.Duke.start(Duke.java:51)
	at duke.Duke.main(Duke.java:33)
10,11c10,12
< 	added:	task 1
< 	Now 1 tasks in Total
---
> 
> 👋 Bye, see ya ~ 
> 
Test result: FAILED
```

Environment: `zsh` shell.

**Comment by l-shihao** [comment]
Additionally, my `input.txt` as below: 
```
todo task 1
todo task b
todo task c
todo task 4
todo task e
done 2 4
list
delete 5 2
list
bye
```
Did change the first line to see if the input is from this file.

**Comment by damithc** [comment]
@l-shihao post the code of the class that uses the Scanner object. Hint: do not create a new Scanner object inside a loop -- reuse the same Scanner object throughout.

**Comment by l-shihao** [comment]
Thank you very much, prof! (It took me one whole day to research 😮‍💨)
Understood, I created one `Scanner` instance every iteration. I shall move the `Scanner` object creation outside. 
Wrong code below as an example: 
```
    private void start() {
        Scanner in = new Scanner(System.in);
        String userInput = in.nextLine();

        switch(userInput.strip()) {
            case "bye":
                return;
            case "list":
                list.print();
                break;
            default:
                strParser.passToCaller(userInput);
        }

        start();
    }
```
After fixed output is what I want: 
```
li@intel text-ui-test % bash runtest.sh
Note: ../src/main/java/duke/ui/Message.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
10,35d9
< 	added:	task 1
< 	Now 1 tasks in Total
< 	added:	task b
< 	Now 2 tasks in Total
< 	added:	task c
< 	Now 3 tasks in Total
< 	added:	task 4
< 	Now 4 tasks in Total
< 	added:	task e
< 	Now 5 tasks in Total
< 	Marked below as DONE:
< 	[T][✓] task b
< 	Marked below as DONE:
< 	[T][✓] task 4
< 	1. [T][ ] task 1
< 	2. [T][✓] task b
< 	3. [T][ ] task c
< 	4. [T][✓] task 4
< 	5. [T][ ] task e
< 	Roger. Below get removed: 
< 	[T][✓] task b
< 	[T][ ] task e
< 	Task completion status: 1 / 3
< 	1. [T][ ] task 1
< 	2. [T][ ] task c
< 	3. [T][✓] task 4
Test result: FAILED

```
